/** @gb/hud: see CONTRACT.md. */
export { Hud } from './hud.ts'
export { HUD_KEYS } from './controls.ts'
export { HudError, type HudErrorCode } from './errors.ts'
export { HUD_CSS } from './style/index.ts'
export { districtShape } from './map/districts.ts'
export type {
  AiFamily,
  AiHealth,
  AiJob,
  AiJobId,
  AiProvider,
  AiTest,
  AiView,
  Carried,
  CodexFact,
  CodexNote,
  CodexPerson,
  CodexPlace,
  CodexView,
  CompassGoal,
  CompassView,
  ConfirmAsk,
  ControlHint,
  CounterOffer,
  CounterView,
  Disposition,
  FailReason,
  HudHandlers,
  HudIntent,
  HudPatch,
  HudWindowName,
  LoaderView,
  Inspecting,
  MapDistrict,
  MapDrawn,
  MapEdge,
  MapFact,
  MapMark,
  MapMarkKind,
  MapMove,
  MapPlot,
  MapProminence,
  MapReading,
  MapReadingKind,
  MapRect,
  MapShape,
  MapSpot,
  MapStation,
  MapSurface,
  MapView,
  MinimapDoor,
  MinimapView,
  Notice,
  NoticeKind,
  NoticeMood,
  NoticeTone,
  OwnedPlace,
  Prompt,
  QuestEntry,
  QuestStatus,
  QuestStep,
  QuestStepState,
  QuestTimer,
  Reward,
  ScreenGame,
  ScreenProgram,
  ScreenView,
  SettingsView,
  TalkMove,
  TalkPatch,
  TalkTurn,
} from './types.ts'
