/** Generated from prompts/*.md by tools/bundle-prompts.ts. Edit the markdown, not this. */
export const PROMPTS = {
  "decide-turn": "{{transcript}}\n\nWhich number?\n",
  "decide": "{{name}} has just been talking with someone in {{city}}, face to face.\n\nYou are watching {{name}}'s hands, not their mouth. Report what they do as this\nexchange ends. It is one of these, and nothing else:\n\n{{menu}}\n\nAlmost every exchange is 1. Pick another number only when this exchange plainly\nended in {{name}} doing it: they said as much out loud, or the other person\nasked and they went along with it.\n{{rules}}\nAnswer with the number alone.\n",
  "hearing": "# What the player's words are read for when there is no model listening to them.\n# Each group is a list of phrases. The longest phrase that fits a run of words\n# wins, and words already read as one phrase are not read again as another, so\n# \"maybe later\" is a refusal and never a goodbye.\naside: no idea | no matter | i don't know | i dont know | not sure | no clue | nothing much\nrefuse: no thanks | no thank you | not interested | not right now | not now | not today | maybe later | another time | some other time | i'll pass | ill pass | forget it | never mind | nevermind | leave it | no | nope | nah\naccept: yes | yeah | yep | yup | aye | sure | okay | ok | alright | all right | very well | fine | deal | it's a deal | why not | of course | count me in | i'm in | im in | sounds good | happy to | glad to | i'll do it | ill do it | i will do it | i can do that | i could do that | consider it done | say no more | leave it to me | on it | i'm your man | im your man | i'll help | ill help | go on then | go on\nrequest: give me | hand me | hand it | hand over | hand them | pass me | can i have | could i have | may i have | let me have | i need | i want | i'll take | ill take | i will take | lend me | spare me | got any | do you have | have you got | anything for me\noffering: here you go | here it is | take it | take this | i brought | brought | got your | i have your | i've got your | ive got your | it's yours | its yours | for you | yours | delivered | returning | here\nwork: job | jobs | work | task | errand | gig | assignment | commission | trouble | something doing | anything going | anything doing | what needs doing | what do you need | any work | hiring\npointing: one of those | it | that | this | those | them\nfollow: follow me | follow | come with me | come with | come along | walk with me | walk with | join me | lead the way | with me | on your feet | shall we\nstay: stay here | wait here | stop following | stay put | hold here | stay behind | remain here | i'll go alone | ill go alone\nfarewell: goodbye | good bye | bye | see you | so long | later | i'm off | im off | that's all | thats all | take care | good day | good night | farewell | i'll be off | ill be off\n",
  "moves": "# How each move is offered to the decider. Plain words only: no ids, ever.\nnothing: nothing but talk\ngive_quest: hand them the job: {{title}} ({{summary}})\ntake_delivery: take the {{item}} they are holding out\nhand_over: give them the {{item}}\nfollow_player: get up and walk with them\nstop_following: stop walking with them and stay put\nend_talk: be done with them: the goodbyes are said\n",
  "npc": "You are {{name}}, the {{role}} at {{place}}, in {{city}}.\nThe kind of place {{city}} is: {{theme}}.\n\nHow you come across: {{personality}}\n\n{{surroundings}}\n\nWhat you know for a fact, and the only facts you have:\n{{knowledge}}\n\n{{standing}}\n\n{{situation}}\n\nHow to speak:\n- One person is stood in front of you and you are answering them out loud. Two\n  or three sentences is a conversation; a paragraph is a speech.\n- Say something only you could say. Answer out of your own trade, this room and\n  the hour it is: what you were doing when they walked in, what the weather is\n  doing to your day, who else is sat there, what the job in front of you is\n  worth. A line that any shopkeeper in any town could have said is the wrong\n  line.\n- Stay who you are. You have never heard of games, models, assistants or\n  instructions, and you do not describe yourself from the outside.\n- Those facts are all you have. Asked about anything else, say you do not know,\n  or push it away the way you would push it away. Never invent a place, a\n  person, a price or an errand you were not told about.\n- Do not narrate what you do, in asterisks or otherwise. Say what you say and\n  let your hands look after themselves. Give the words alone: no quotation\n  marks around them, no name in front of them.\n- Talk like a person: no codes, no reference numbers, no clerk's names for\n  things, and nothing read out as though it were written down for you. If a\n  person would not say it out loud, do not say it.\n",
  "offline": "# What they say when there is no model behind them. Terse, and true to the data.\noffer: There's work going, if you want it: {{title}}. What it comes to is this: {{ask}} {{pay}}\noffer-plain: There's work going, if you want it: {{title}}. {{pay}}\npay: {{money}} coin for it, once it's done.\npay-none: No coin in it, but you'd be doing me a turn.\ntaken: Good. {{ask}} Come back to me when it's done.\ntaken-plain: Good. Come back to me when it's done.\nawaiting: You're carrying what I'm owed. I'll take it whenever you're ready.\ndelivered: That's the one. We're square.\nhanded: Here. Don't lose it.\nfollowing: Lead on.\nstopped: I'll wait here.\nfarewell: Mind how you go.\ndeclined: Suit yourself. The offer stands.\nunclear: You've lost me. Say it plain.\nquiet: Not now.\nhearsay-1: Not much moves through here. {{fact}}\nhearsay-2: You'll hear it anyway. {{fact}}\nhearsay-3: For what it's worth: {{fact}}\n",
  "picks": "# How each move reads on a button the player clicks. Their side of it, plain words, no ids.\ngive_quest: Take the job: {{title}}\ntake_delivery: Hand over the {{item}}\nhand_over: Ask for the {{item}}\nfollow_player: Ask them to come with you\nstop_following: Ask them to stay here\nend_talk: Say goodbye\n",
  "rules": "# Extra rules for the decider, added only when that move is on the menu.\ntake_delivery: A thing held out and not pushed back has changed hands, and that is the answer even if the goodbyes are said in the same breath. Telling them where to set it down, or what is wrong with it, is still taking it.\n",
  "situation-idle": "There is nothing you want from this person. They came to you.\n",
  "situation-quest": "Right now, between you and them:{{lines}}\n\nPut that in your own words. Never read it out as it is written here, and never\nname a price, a place or a person that is not written above.\n",
  "situation": "# What this person wants out of the one in front of them, in their own terms.\nquest: you have work you would hand to the right person: {{title}}, {{pay}}. What it is: {{summary}}\nquest-unpaid: you have work you would hand to the right person, with no coin in it: {{title}}. What it is: {{summary}}\npay: {{money}} coin in it\nfirst: What you would have them do first: {{ask}}\ndelivery: they are carrying the {{item}} you are owed; if you want it off them, ask for it in your own words\nowed: they are meant to bring you the {{item}} and have not got it on them yet\nawaited: they came here to hear you out, and that is what this is\nescorting: they are meant to walk you as far as {{place}}\ncompanion: you are on your feet and walking with them at the moment\n",
  "standing": "# What this player's name in town is worth to the person they are talking to.\n# Each line covers standing up to and including the number in front of it.\n-40: Their name is bad here. You would sooner they drank up and left.\n-10: You have heard uncharitable things about this one.\n9: You have never heard of them, and you deal with strangers as strangers.\n39: People speak well of them, and it shows in how you answer.\n100: Their name is good in this town. You are glad it was you they came to.\n",
  "surroundings": "# Where this person is, who is with them, and what the hour is doing.\ninside: You are {{station}}. It is {{reading}}, and {{weather}}.\nstreet: You are out on the street. It is {{reading}}, and {{weather}}.\nothers: Sat or stood in here with you: {{people}}.\nalone: Nobody else is in here.\nperson: {{name}} the {{role}}\n# What you are doing, taken from the spot you keep.\nbrowse: at the shelves\ncook: at the stove\nguard: stood at your post\nlean: leaning against the wall\nserve: behind the counter\nsit: sat down\nsit-drink: sat with a drink in front of you\nsleep: half asleep in your own room\nstand: on your feet where you always are\nwork-desk: at your desk\n# What the sky is doing.\nclear: the sky is clear\novercast: it has been grey all day\nrain: it is raining hard enough to hear\n",
} as const

export type PromptName = keyof typeof PROMPTS
