/** @gb/scene: turning a world into something you can stand in. See CONTRACT.md. */
export { buildCity, storeyHeight, type CityBuild, type CityOptions } from './city.ts'
export { type Standing } from './spawn.ts'
export { CityBuilding, type BuildingStep } from './batch/building.ts'
export { plotOf } from './batch/batcher.ts'
export { buildInterior, type InteriorBuild } from './interior.ts'
export { STEP_OVER_HEIGHT } from './blockers.ts'
export { PropFootprint } from './footprint.ts'
export { itemOf } from './pickups.ts'
export { Greybox, type BuildingSize, type Dressing, type SurfacePart, type SurfaceSize } from './dressing.ts'
export { type LightEmitter } from './lights/emitter.ts'
export { CityLights, LIVE_LIGHTS, type PlacedEmitter, type Shadowing } from './lights/city-lights.ts'
export { ROOM_LIGHTS, ROOM_SHADOWS, RoomLight } from './lights/room-lights.ts'
export { DETAIL_RADIUS, SHELL_RADIUS } from './lod/near.ts'
export { STREAM_BUILDS } from './lod/ring.ts'
export { VISITOR_CELL, type VisitorCell } from './visitors.ts'
export { BOUNCE } from './fill.ts'
export { CEILING_HEIGHT } from './shell.ts'
export { MARKING, type Marking, type MarkingKind, type MarkingPaint } from './markings.ts'
export { BAND, CLEARANCE, CLUTTER, CLUTTER_MAX_HEIGHT, type ClutterKind } from './clutter/catalog.ts'
export { CLUTTER_DENSITY, type ClutterDensity, type ClutterPiece } from './clutter/plan.ts'
export { SURFACE } from './street/sizes.ts'
