/** @gb/kitbash: buildings that look like buildings, from the Downtown kit. See CONTRACT.md. */
export { KitDressing } from './dressing.ts'
export { loadKit } from './kit/load.ts'
export { placeholderKit } from './kit/placeholder.ts'
export { DEFAULT_THEME, KitLibrary, type KitPart } from './kit/library.ts'
export { flavourOf, type Flavour } from './look/flavour.ts'
export { TONES, type Tone } from './look/tones.ts'
export { GroundLibrary, type GroundMaps } from './ground/library.ts'
export { GROUND_LOOKS, GROUND_TEXTURES, GROUND_TEXTURE_IDS, PAVEMENT_TONES, type GroundLook, type GroundTexture, type GroundTextureId } from './ground/surfaces.ts'
export { KitIncomplete, KitUnmergeable } from './kit/error.ts'
export { FAKE_INTERIOR, GLASS, isGlazed, KIT_MATERIALS, MODULE, nodeNamesOf, PIECE_IDS, PIECES, RELIEF, type Piece, type PieceId } from './catalog/pieces.ts'
export { RECIPES, type Course, type Recipe } from './catalog/recipes.ts'
export { CityNight } from './night/night.ts'
export { nightLook, type NightLook } from './night/clock.ts'
export { ROOM_ATTRIBUTES, type Room } from './night/room.ts'
export { LAMP_SPACING, lampSpots, type LampSpot } from './street/layout.ts'
export { STREETLIGHT } from './street/lamp/design.ts'
export { lightsFor, signsFor } from './signage.ts'
export { SIGN, type Mount, type Sign, type SignKind, type Written } from './sign/sign.ts'
export { type LightEmitter } from './sign/light.ts'
export { DOORLAMP } from './sign/doorlamp.ts'
export { LETTER_SHARE } from './sign/fascia.ts'
export { SIGNAGE, TRADE_WORD, type Signage } from './sign/trade.ts'
export { GLYPH_KEYS, MARKS, SOLID } from './sign/glyphs.ts'
export { cellAt, cellUv } from './sign/atlas.ts'
export { SIGN_ATTRIBUTES } from './sign/material.ts'
