/** @gb/kitbash: buildings that look like buildings, from the Downtown kit. See CONTRACT.md. */
export { KitDressing } from './dressing.ts'
export { loadKit } from './kit/load.ts'
export { placeholderKit } from './kit/placeholder.ts'
export { KitLibrary, type KitPart } from './kit/library.ts'
export { GroundLibrary, type GroundMaps } from './ground/library.ts'
export { GROUND_LOOKS, GROUND_TEXTURES, GROUND_TEXTURE_IDS, type GroundLook, type GroundTexture, type GroundTextureId } from './ground/surfaces.ts'
export { KitIncomplete, KitUnmergeable } from './kit/error.ts'
export { FAKE_INTERIOR, GLASS, isGlazed, KIT_MATERIALS, MODULE, nodeNamesOf, PIECE_IDS, PIECES, RELIEF, type Piece, type PieceId } from './catalog/pieces.ts'
export { FURNITURE, FURNITURE_IDS, LAMP, LAMP_LENS, LAMP_POST, type FurnitureId, type FurniturePiece } from './catalog/furniture.ts'
export { RECIPES, type Course, type Recipe } from './catalog/recipes.ts'
export { CityNight } from './night/night.ts'
export { nightLook, type NightLook } from './night/clock.ts'
export { ROOM_ATTRIBUTES, type Room } from './night/room.ts'
export { LAMP_SPACING, lampSpots, type LampSpot } from './street/layout.ts'
