/** Generated from prompts/*.md by tools/bundle-prompts.ts. Edit the markdown, not this. */
export const PROMPTS = {
  "describe-item": "Write the object.\n\nTheme: {{theme}}\nWhat it physically is: {{archetype}}\n\nGive it a name a person would use for it and one sentence describing it. It can\nbe ordinary. Do not make it magical or valuable unless the theme calls for it.\n",
  "describe-npc": "Write the person who works or spends their time here.\n\nTheme: {{theme}}\nPlace: {{placeName}} ({{placeKind}})\nTheir role there: {{role}}\n\nGive them a name, one or two sentences of personality, and between two and four\nthings they know. What they know should be things overheard or noticed from\nwhere they are: who owes what, who was in last night, what is late, what is\nbroken. Keep each one to a single sentence.\n",
  "name-city": "Name the city.\n\nTheme: {{theme}}\n\nTwo or three words at most, the kind of name that would be on a road sign.\n",
  "name-place": "Name this building.\n\nTheme: {{theme}}\nKind of building: {{kind}}\n\nName it the way its owner would have named it. A bar and an office are named\nvery differently. Do not mention the kind of building in the name unless that\nis how such places are really named.\n",
  "system": "You are the author of a small city in a first-person game. The player walks its\nstreets, goes into its buildings, talks to the people in them, and runs errands\nfor them.\n\nYou are writing the invented part only: names, personalities, what people know,\nand the errands they hand out. Someone else has already decided where every\nstreet and building goes. Never describe geometry, coordinates, sizes or\ndistances.\n\nAnswer only by calling the tool you are given. Do not write prose around it.\n\nHouse style:\n- Plain, specific, human. A bar is \"The Copper Wheel\", not \"The Mystical Tavern\n  of Wonders\".\n- Fit the theme you are handed, including its period and its register.\n- Names are pronounceable and short. No titles, no epithets, no fantasy\n  apostrophes unless the theme asks for them.\n- Personalities are one or two sentences about how someone behaves, not a\n  biography.\n- What a person knows is what they could plausibly have heard from where they\n  stand all day.\n",
  "write-quests": "Write the errands the people of this city hand out.\n\nTheme: {{theme}}\nCity: {{cityName}}\n\nHere is everyone in it and everything lying around, by id:\n\n{{places}}\n\nWrite {{questCount}} quests, the first one the main one. Each is a short chain\nof steps the player performs in order.\n\nRules that make a quest playable, and that will be checked:\n- Use only the ids listed above. Inventing an id fails the quest.\n- Every step id is unique inside its quest and looks like step_0001.\n- A step's `next` names the step that follows. The last step in a chain is a\n  `complete` step with an empty `next`.\n- Before a `deliver` step, an earlier step on the same path must `collect` that\n  same item.\n- The person who gives the quest must be somewhere the player can reach, and\n  the first step is normally talking to them.\n- If an item has an owner, taking it is stealing: set `allowSteal` to true and\n  expect the reward to reflect it.\n\nWrite the objective lines in the second person and keep them short: \"Take the\nledger to Mara at the Copper Wheel\".\n",
} as const

export type PromptName = keyof typeof PROMPTS
