/** @gb/prefab: whole buildings from a committed pack, one draw for the city. See CONTRACT.md. */
export { HEIGHT_TOLERANCE, PROUD } from './fit.ts'
export { bucketOf, bucketKey, everyBucket, heightOf, DEPTHS, FRONTS, STOREYS, type Bucket } from './bucket.ts'
export { Catalogue, CatalogueSchema, InvalidCatalogue, type CatalogueDoc, type Design, type ModelSpec } from './catalogue.ts'
export { PrefabDressing, type BuildingSize } from './dressing.ts'
export { Library, LibraryIncomplete, type LibrarySpec } from './library.ts'
export { loadPrefab, PackChanged } from './load.ts'
export { FACADE, InteriorWindows, ROOM, SHOPFRONT, glassShareOf, windowsOn, type Glazing, type WindowKind } from './interior.ts'
export { prefabMaterial, type PrefabAtlas } from './material.ts'
export { ROOM_BANKS, ROOM_PICTURES, ROOM_SIZE, type Bank } from './rooms.ts'
export { SCREEN, WallScreens, type Panel } from './display.ts'
export { DISPLAY_FINISH, SCREEN_PICTURES, SCREEN_SIZE } from './screens.ts'
export { GLOW, LAYER_ATTRIBUTE, MATERIAL_NAME } from './pack.ts'
export { orient, turnsFor } from './orient.ts'
