/** @gb/traffic: cars driving a generated city. See CONTRACT.md. */
export { Traffic } from './traffic.ts'
export { LaneGraph, type GraphShape, type Roads } from './lane-graph.ts'
export { Junction, Lane, Link, Track, type Turn } from './track.ts'
export { CAR_MODELS, type CarModel, type TrafficOptions } from './settings.ts'
export { CarPack } from './car-pack.ts'
export { CARS_FILE, CAR_FOOTPRINT, CAR_PARTS, partName, type CarPart } from './pack-layout.ts'
export type { CarBodies, CarBody, CarSpawn } from './bodies.ts'
export type { Obstacle, Obstacles } from './obstacles.ts'
export type { CarView } from './car.ts'
export { CarPackError, type CarPackErrorCode, type TrafficError } from './errors.ts'
export type { Point } from './geometry.ts'
